### ISSUE TITLE
Refactor terraform cache to store the files from .resource folder instead of tar.gz

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#116]

**Comment by ddimitrioglo** [comment]
This could be done by changing cache component behaviour (this will affect all the components which are using cache as sub-component) or reimplement this logic in terraform component.

@eistrati what path we have to chose?

**Comment by eistrati** [comment]
@ddimitrioglo I would suggest to implement this as separate component and integrate with terraform first, and after that see how we can "smoothly" replace internal cache with external (this new) component. Will that work?

**Comment by avozicov** [comment]
Test **Passed**
Acceptance Criteria:
- user should be able to configure cache in .recink.yml under terraform component
- once s3 bucket is defined it is expected that state and plan files will be stored there in the right format (.resources/terraform.tfstate | .tfplan)
- on the next `recink run terraform` execution it is expected to use cached files from remote bucket instead of local directory

**Comment by eistrati** [comment]
Checked.
