### ISSUE TITLE
Add capability to send list type variable to terraform *.tfvars

### ISSUE THREAD

**Issue by euliancom** [MitocGroup/recink#94]
example stable.tfvars
________________________________
aws_region = "us-west-2"
db_identifiers = ["wos-test1","wos-test2","wos-test3"]
____________________________________________

db_identifiers = [ type = "list"] it is a list of rds identifier

when I run terraform script, it would be nice to change the list type variables too

example:

recink run terraform --tf-vars="db_identifiers:[here must be the list]"

**Comment by eistrati** [comment]
@ddimitrioglo In order to pass a list, you must use explicit values. Referencing to above example, it would look like this:

`recink run terraform --tf-vars="db_identifiers.0:wos-test1,db_identifiers.1:wos-test2,db_identifiers.2:wos-test3"`

or

`recink run terraform --tf-vars="db_identifiers:['wos-test1','wos-test2','wos-test3']"`

**Comment by ddimitrioglo** [comment]
following variant is implemented 
`--tf-vars="db_identifiers.0:wos-test1,db_identifiers.1:wos-test2,db_identifiers.2:wos-test3"`

**Comment by ddimitrioglo** [comment]
@eistrati I think it can be closed

**Comment by eistrati** [comment]
Checked.
